[package]
name = "execguard-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
execguard-parser.workspace = true
execguard-storage.workspace = true

tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
anyhow.workspace = true